"""categories and contact_categories

Makes industry category a first-class concept: two tables, the five seeded
categories, and the provenance columns an import undo needs.

Why the seed lives in the migration rather than a script: `alembic upgrade head`
on an empty database has to produce a usable app, and a five-row lookup table
with no rows in it is not a schema that works — it is a schema with a manual
step attached, and the manual step is the one that gets skipped on the
production box. The seed is idempotent, so re-running it changes nothing.

The seed values are written out literally rather than imported from
`app.models.category`. A migration is a historical record of what was applied;
importing today's constants would make yesterday's migration mean something new
the next time someone edits them.

`color_token` is a token, not a hex — see the model for why four hues is the
ceiling.

Nothing here touches `ix_contacts_phone`. The three added columns are nullable
and additive, and the downgrade drops them; on SQLite `batch_alter_table`
recreates the table, which takes the foreign key with it.

Revision ID: 4119449a9937
Revises: f69dc078ee13
Create Date: 2026-08-19 18:09:11.651472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4119449a9937'
down_revision: Union[str, None] = 'f69dc078ee13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# slug, label, color_token — order is the display order.
SEED_CATEGORIES = (
    ("food_service",  "Food Service",          "s1"),
    ("equipment",     "Equipment & Machinery", "s2"),
    ("estates",       "Estates",               "s3"),
    ("memorabilia",   "Memorabilia",           "s4"),
    ("general",       "General Merchandise",   "neutral"),
)


def _seed_categories() -> None:
    """Insert any of the five that are missing. Safe to run repeatedly."""
    categories = sa.table(
        "categories",
        sa.column("slug", sa.String),
        sa.column("label", sa.String),
        sa.column("color_token", sa.String),
        sa.column("sort_order", sa.Integer),
        sa.column("is_active", sa.Integer),
    )

    bind = op.get_bind()
    existing = {row[0] for row in bind.execute(sa.select(categories.c.slug))}

    rows = [
        {"slug": slug, "label": label, "color_token": token,
         "sort_order": order, "is_active": 1}
        for order, (slug, label, token) in enumerate(SEED_CATEGORIES, start=1)
        if slug not in existing
    ]
    if rows:
        op.bulk_insert(categories, rows)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('color_token', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=50), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_slug'), ['slug'], unique=True)

    op.create_table('contact_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('added_at', sa.String(length=50), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'category_id', name='uq_contact_category')
    )
    with op.batch_alter_table('contact_categories', schema=None) as batch_op:
        batch_op.create_index('idx_contact_category_category', ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_categories_id'), ['id'], unique=False)

    with op.batch_alter_table('contact_list_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_contact', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_tag', sa.Integer(), nullable=True))

    with op.batch_alter_table('contact_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_contact_lists_category', 'categories', ['category_id'], ['id'],
            ondelete='SET NULL',
        )

    # ### end Alembic commands ###

    _seed_categories()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # No drop_constraint for the foreign key: batch mode rebuilds the table from
    # the remaining columns, so dropping category_id removes it. Naming it in a
    # separate drop_constraint fails on SQLite, where it has no independent
    # existence.
    with op.batch_alter_table('contact_lists', schema=None) as batch_op:
        batch_op.drop_column('category_id')

    with op.batch_alter_table('contact_list_members', schema=None) as batch_op:
        batch_op.drop_column('created_tag')
        batch_op.drop_column('created_contact')

    with op.batch_alter_table('contact_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_categories_id'))
        batch_op.drop_index('idx_contact_category_category')

    op.drop_table('contact_categories')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_slug'))
        batch_op.drop_index(batch_op.f('ix_categories_id'))

    op.drop_table('categories')
    # ### end Alembic commands ###
