"""initial schema

Baseline capture of the skeleton's seven tables — contacts, contact_lists,
contact_list_members, campaigns, sms_messages, blocked_numbers, app_settings —
as they already existed via Base.metadata.create_all(). Nothing here is new;
this migration exists so that from module 1 onward every schema change has a
reviewable, reversible script instead of appearing by side effect at import
time.

Note `ix_contacts_phone` is unique. That single index IS the dedup guarantee —
it is what stops the same person entering the list five times from five
imports. Any later migration touching it is an escalation, not a refactor.

Revision ID: f69dc078ee13
Revises:
Create Date: 2026-08-18 20:16:30.556105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f69dc078ee13'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_settings_key'), ['key'], unique=True)

    op.create_table('blocked_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('blocked_at', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blocked_numbers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blocked_numbers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocked_numbers_phone'), ['phone'], unique=True)

    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=255), nullable=False),
    sa.Column('audience_label', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_recipients', sa.Integer(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('skipped_count', sa.Integer(), nullable=True),
    sa.Column('estimated_segments', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.String(length=50), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('started_at', sa.String(length=50), nullable=True),
    sa.Column('completed_at', sa.String(length=50), nullable=True),
    sa.Column('abort_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_id'), ['id'], unique=False)

    op.create_table('contact_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=50), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_lists_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_lists_name'), ['name'], unique=True)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('external_ref', sa.String(length=255), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=50), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.Column('last_messaged_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index('idx_contacts_active', ['is_active'], unique=False)
        batch_op.create_index('idx_contacts_source', ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_phone'), ['phone'], unique=True)

    op.create_table('contact_list_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.String(length=50), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['contact_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'contact_id', name='uq_list_contact')
    )
    with op.batch_alter_table('contact_list_members', schema=None) as batch_op:
        batch_op.create_index('idx_member_list', ['list_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_list_members_id'), ['id'], unique=False)

    op.create_table('sms_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('segments', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.String(length=50), nullable=True),
    sa.Column('delivered_at', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_messages', schema=None) as batch_op:
        batch_op.create_index('idx_sms_campaign', ['campaign_id'], unique=False)
        batch_op.create_index('idx_sms_sent_at', ['sent_at'], unique=False)
        batch_op.create_index('idx_sms_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_messages_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_messages_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_messages_id'))
        batch_op.drop_index(batch_op.f('ix_sms_messages_external_id'))
        batch_op.drop_index('idx_sms_status')
        batch_op.drop_index('idx_sms_sent_at')
        batch_op.drop_index('idx_sms_campaign')

    op.drop_table('sms_messages')
    with op.batch_alter_table('contact_list_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_list_members_id'))
        batch_op.drop_index('idx_member_list')

    op.drop_table('contact_list_members')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_phone'))
        batch_op.drop_index(batch_op.f('ix_contacts_id'))
        batch_op.drop_index('idx_contacts_source')
        batch_op.drop_index('idx_contacts_active')

    op.drop_table('contacts')
    with op.batch_alter_table('contact_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_lists_name'))
        batch_op.drop_index(batch_op.f('ix_contact_lists_id'))

    op.drop_table('contact_lists')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_id'))

    op.drop_table('campaigns')
    with op.batch_alter_table('blocked_numbers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocked_numbers_phone'))
        batch_op.drop_index(batch_op.f('ix_blocked_numbers_id'))

    op.drop_table('blocked_numbers')
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_settings_key'))
        batch_op.drop_index(batch_op.f('ix_app_settings_id'))

    op.drop_table('app_settings')
    # ### end Alembic commands ###
